mongo:
  authMechanism: "SCRAM-SHA-1"
  host: mongodb://127.0.0.1
  port: 27017
  user: "admin"
  password: "admin"
  cacert: ""
s3:
  url: "https://localhost"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 5
  cacert: "./dev_tools/certs/ca.pem"
db:
  host: "localhost"
  port: 5432
  user: "lega_in"
  password: "lega_in"
  database: "lega"
  cacert: "./dev_tools/certs/ca.pem"
  clientCert: "./dev_tools/certs/client.pem"
  clientKey: "./dev_tools/certs/client-key.pem"
  sslmode: "verify-ca"
loglevel: "info"
