mongo:
  authMechanism: "SCRAM-SHA-1"
  host: mongodb://127.0.0.1
  port: 27017
  user: "admin"
  password: "admin"
  cacert: ""
s3:
  url: "http://localhost"
  port: 9000
  accesskey: "access"
  secretkey: "secretkey"
  bucket: "inbox"
  chunksize: 5
loglevel: "info"
