version: "3.7"
services:
  database:
    image: "mongo"
    container_name: "mongo"
    restart: "on-failure"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
    volumes:
      - "data:/data/db"
    ports:
      - "27017:27017"
  s3:
    command: server /data
    image: minio/minio:RELEASE.2021-02-01T22-56-52Z
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=access
      - MINIO_SECRET_KEY=secretkey
volumes:
  data:
